"""Centralized node IDs used by the risk core MVP.

The legacy implementation stores these IDs directly in dataframe columns.  The
new modules keep IDs here so external scenario files can use semantic names.
"""

TOTAL_RISK = 10000000

INTERNAL_RISK = 20000000
EXTERNAL_RISK = 20000001

INTERNAL_STATIC_RISK = 30000000
INTERNAL_DYNAMIC_RISK = 30000001
EXTERNAL_STATIC_RISK = 30000010
EXTERNAL_DYNAMIC_RISK = 30000011

PATIENT_ATTRIBUTE_RISK = 40000000
AGE_ATTRIBUTE_RISK = 40000001
STANDING_RISK = 40000010
WHEELCHAIR_BRAKE_RELEASE_RISK = 40000011
WHEELCHAIR_MOVE_RISK = 40000012
LOSING_BALANCE_RISK = 40000013
HAND_MOVEMENT_RISK = 40000014
COUGHING_RISK = 40000015
TOUCHING_FACE_RISK = 40000016
IV_POLE_RISK = 40000100
WHEELCHAIR_RISK = 40000101
HANDRAIL_DISTANCE_RISK = 40000102
STAFF_DISTANCE_RISK = 40000110
STAFF_NOT_WATCHING_RISK = 40000111

IS_PATIENT = 50000000
AGE_CATEGORY = 50000010
POSE_STANDING_DEGREE = 50000100
POSE_TRUNK_TILT = 50000101
POSE_WRIST_DISTANCE_FROM_HIP = 50000102
POSE_ANKLE_SPREAD = 50000103

IV_POLE_X = 50001000
IV_POLE_Y = 50001001
WHEELCHAIR_X = 50001010
WHEELCHAIR_Y = 50001011
HANDRAIL_X = 50001020
HANDRAIL_Y = 50001021
STAFF_X = 50001100
STAFF_Y = 50001101
STAFF_VX = 50001110
STAFF_VY = 50001111

PERSON_X = 60010000
PERSON_Y = 60010001
PERSON_HEIGHT_MAX = 60010002

BACKGROUND_DIFFERENCE = 70000000

ACTION_RISK_NODES = (
    STANDING_RISK,
    WHEELCHAIR_BRAKE_RELEASE_RISK,
    WHEELCHAIR_MOVE_RISK,
    LOSING_BALANCE_RISK,
    HAND_MOVEMENT_RISK,
    COUGHING_RISK,
    TOUCHING_FACE_RISK,
)

OBJECT_RISK_NODES = (
    IV_POLE_RISK,
    WHEELCHAIR_RISK,
    HANDRAIL_DISTANCE_RISK,
)

STAFF_RISK_NODES = (
    STAFF_DISTANCE_RISK,
    STAFF_NOT_WATCHING_RISK,
)

FACTOR_RISK_NODES = ACTION_RISK_NODES + OBJECT_RISK_NODES + STAFF_RISK_NODES

ATTRIBUTE_RISK_NODES = (
    PATIENT_ATTRIBUTE_RISK,
    AGE_ATTRIBUTE_RISK,
)

UPPER_RISK_NODES = (
    INTERNAL_STATIC_RISK,
    INTERNAL_DYNAMIC_RISK,
    EXTERNAL_STATIC_RISK,
    EXTERNAL_DYNAMIC_RISK,
    INTERNAL_RISK,
    EXTERNAL_RISK,
    TOTAL_RISK,
)

EVALUATED_OUTPUT_NODES = (
    TOTAL_RISK,
    INTERNAL_RISK,
    EXTERNAL_RISK,
    INTERNAL_STATIC_RISK,
    INTERNAL_DYNAMIC_RISK,
    EXTERNAL_STATIC_RISK,
    EXTERNAL_DYNAMIC_RISK,
) + ATTRIBUTE_RISK_NODES + FACTOR_RISK_NODES

SEMANTIC_NAME_TO_NODE_ID = {
    "total_risk": TOTAL_RISK,
    "internal_risk": INTERNAL_RISK,
    "external_risk": EXTERNAL_RISK,
    "internal_static_risk": INTERNAL_STATIC_RISK,
    "internal_dynamic_risk": INTERNAL_DYNAMIC_RISK,
    "external_static_risk": EXTERNAL_STATIC_RISK,
    "external_dynamic_risk": EXTERNAL_DYNAMIC_RISK,
    "standing_risk": STANDING_RISK,
    "wheelchair_brake_release_risk": WHEELCHAIR_BRAKE_RELEASE_RISK,
    "wheelchair_move_risk": WHEELCHAIR_MOVE_RISK,
    "losing_balance_risk": LOSING_BALANCE_RISK,
    "hand_movement_risk": HAND_MOVEMENT_RISK,
    "coughing_risk": COUGHING_RISK,
    "touching_face_risk": TOUCHING_FACE_RISK,
    "iv_pole_risk": IV_POLE_RISK,
    "wheelchair_risk": WHEELCHAIR_RISK,
    "handrail_distance_risk": HANDRAIL_DISTANCE_RISK,
    "staff_distance_risk": STAFF_DISTANCE_RISK,
    "staff_not_watching_risk": STAFF_NOT_WATCHING_RISK,
    "background_difference": BACKGROUND_DIFFERENCE,
}

NODE_ID_TO_SEMANTIC_NAME = {
    node_id: name for name, node_id in SEMANTIC_NAME_TO_NODE_ID.items()
}
